#!/usr/bin/env node
/**
 * SEO generator — single source of truth for per-page metadata.
 *
 * Usage: node scripts/generate-seo.mjs
 *
 * For every route below this script:
 *   - injects (or updates) an idempotent <!-- seo:managed --> block in the
 *     matching HTML entry file: <title>, description, canonical,
 *     Open Graph + Twitter card tags, and noindex for member-only pages
 * - regenerates public/sitemap.xml (public routes only)
 * - regenerates public/robots.txt
 *
 * Re-running is always safe: managed blocks are replaced wholesale.
 */
import fs from 'node:fs';
import path from 'node:path';

const SITE_URL = 'https://sheffieldclimbing.org';
const OG_IMAGE = `${SITE_URL}/climbing%20team%20logo.png`;

/** memberOnly pages get noindex + are excluded from the sitemap */
const PAGES = [
    {
        file: 'index.html',
        path: '/',
        title: 'USMC | University of Sheffield Mountaineering & Climbing Club',
        description:
            'University of Sheffield Mountaineering & Climbing Club — weekly indoor sessions, competitions, outdoor trips and a friendly community for every grade of climber.'
    },
    {
        file: 'about.html',
        path: '/about',
        title: 'About Indoor & Competitions | USMC',
        description:
            'Meet the USMC Indoor & Competitions committee and find out how our training, comps and socials are organised.'
    },
    {
        file: 'schedule.html',
        path: '/schedule',
        title: 'Schedule | USMC',
        description: 'Upcoming USMC climbing sessions, training and socials — browse the calendar and book your place.'
    },
    {
        file: 'competitions.html',
        path: '/competitions',
        title: 'Indoor & Competitions | USMC',
        description:
            'BUCS, NUID, NUBS and varsity competitions — how USMC trains, selects teams and competes across the UK.'
    },
    {
        file: 'beginners.html',
        path: '/beginners',
        title: "Beginner's Guide | USMC",
        description:
            'New to climbing? Everything beginners need to know before their first USMC session — gear, walls, costs and what to expect.'
    },
    {
        file: 'walls.html',
        path: '/walls',
        title: 'Local Walls | USMC',
        description:
            'Sheffield climbing walls the club trains at — locations, student discounts and what each wall is best for.'
    },
    {
        file: 'faq.html',
        path: '/faq',
        title: 'FAQ | USMC',
        description:
            'Answers to common questions about joining and climbing with the University of Sheffield Mountaineering & Climbing Club.'
    },
    {
        file: 'gallery.html',
        path: '/gallery',
        title: 'Gallery | USMC',
        description: 'Photos from USMC sessions, competitions and trips.'
    },
    {
        file: 'login.html',
        path: '/login',
        title: 'Member Access | USMC',
        description: 'Sign in to your USMC member account.',
        memberOnly: true
    },
    {
        file: 'dashboard.html',
        path: '/dashboard',
        title: 'Member Dashboard | USMC',
        description: 'Your USMC membership dashboard.',
        memberOnly: true
    },
    {
        file: 'admin.html',
        path: '/admin',
        title: 'Committee Portal | USMC',
        description: 'USMC committee administration.',
        memberOnly: true
    },
    {
        file: 'elections.html',
        path: '/dashboard/elections',
        title: 'Elections | USMC',
        description: 'USMC committee elections — candidates, manifestos and voting.',
        memberOnly: true
    },
    {
        file: 'gallery-manager.html',
        path: '/dashboard/gallery-manager',
        title: 'Gallery Manager | USMC',
        description: 'Manage USMC gallery photos.',
        memberOnly: true
    },
    {
        file: 'social-post.html',
        path: '/dashboard/social-post',
        title: 'Generate Social Post | USMC',
        description: 'Generate USMC social media announcement slides.',
        memberOnly: true
    },
    {
        file: 'verify.html',
        path: '/verify',
        title: 'Verify Membership | USMC',
        description: 'Verify a USMC membership card.',
        memberOnly: true
    }
];

function escapeHtmlAttr(s) {
    return String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
}

function buildManagedBlock(page) {
    const url = `${SITE_URL}${page.path === '/' ? '' : page.path}`;
    const lines = [
        '<!-- seo:managed (generated by scripts/generate-seo.mjs - do not hand-edit inside these markers) -->',
        `<title>${escapeHtmlAttr(page.title)}</title>`,
        `<meta name="description" content="${escapeHtmlAttr(page.description)}">`,
        `<link rel="canonical" href="${url}">`,
        `<meta property="og:title" content="${escapeHtmlAttr(page.title)}">`,
        `<meta property="og:description" content="${escapeHtmlAttr(page.description)}">`,
        `<meta property="og:type" content="website">`,
        `<meta property="og:url" content="${url}">`,
        `<meta property="og:image" content="${OG_IMAGE}">`,
        `<meta property="og:site_name" content="USMC">`,
        `<meta name="twitter:card" content="summary_large_image">`,
        `<meta name="twitter:title" content="${escapeHtmlAttr(page.title)}">`,
        `<meta name="twitter:description" content="${escapeHtmlAttr(page.description)}">`,
        `<meta name="twitter:image" content="${OG_IMAGE}">`
    ];
    if (page.memberOnly) {
        lines.push('<meta name="robots" content="noindex, nofollow">');
    }
    lines.push('<!-- /seo:managed -->');
    return lines.join('\n    ');
}

function injectSeo(htmlFile, block) {
    const filePath = path.resolve(htmlFile);
    let html = fs.readFileSync(filePath, 'utf8');

    // Remove any previous managed block(s)
    html = html.replace(/[ \t]*<!-- seo:managed[\s\S]*?\/seo:managed -->\n?/g, '');

    // Remove stray duplicate <title> tags outside the managed block
    html = html.replace(/^[ \t]*<title>[^<]*<\/title>\n/m, '');
    html = html.replace(/<title>[^<]*<\/title>/, ''); // first remaining title anywhere

    // Insert the managed block just before </head>
    if (!html.includes('</head>')) {
        console.error(`  ! ${htmlFile}: no </head> found, skipped`);
        return;
    }
    html = html.replace('</head>', `    ${block}\n</head>`);
    fs.writeFileSync(filePath, html);
    console.log(`  ✓ ${htmlFile}`);
}

// --- 1. Inject managed blocks ---
console.log('Injecting SEO blocks:');
for (const page of PAGES) {
    injectSeo(path.resolve('src', '..', page.file), buildManagedBlock(page));
}
// beta-gate shell is not indexed and needs no SEO block

// --- 2. Sitemap (public routes only) ---
const today = new Date().toISOString().slice(0, 10);
const sitemapEntries = PAGES.filter((p) => !p.memberOnly)
    .map(
        (p) => `    <url>
        <loc>${SITE_URL}${p.path === '/' ? '' : p.path}</loc>
        <lastmod>${today}</lastmod>
        <changefreq>weekly</changefreq>
    </url>`
    )
    .join('\n');
fs.writeFileSync(
    path.resolve('public', 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries}
</urlset>
`
);
console.log('✓ public/sitemap.xml');

// --- 3. Robots ---
fs.writeFileSync(
    path.resolve('public', 'robots.txt'),
    `User-agent: *
Allow: /
Disallow: /dashboard
Disallow: /admin
Disallow: /api

Sitemap: ${SITE_URL}/sitemap.xml
`
);
console.log('✓ public/robots.txt');
